Repository learningtapestry/lcms-engine, pull requests merged in 2019-05, with the labels that each got.

#44 Upgrade AirBrake notifier
  lcms-engine.gemspec
Labels: refactoring

#45 (openscied-lcms#266) updates for gdoc processing
  app/services/lcms/engine/google/drive_service.rb
  app/services/lcms/engine/google/script_service.rb
  lib/document_exporter/gdoc/base.rb
Labels: enhancement

#46 (openscied-lcms#334) Check&fix reimport with gdoc templates
  app/services/lcms/engine/html_sanitizer.rb
Labels: bug

#47 Refactor Metadata tables inheritance
  .rubocop.yml
  lib/doc_template/tables/activity.rb
  lib/doc_template/tables/agenda.rb
  lib/doc_template/tables/base.rb
  lib/doc_template/tables/material_metadata.rb
  lib/doc_template/tables/metadata.rb
  lib/doc_template/tables/section.rb
  lib/doc_template/tables/target.rb
  lib/lt/lcms/metadata/base_service.rb
  lib/lt/lcms/metadata/service.rb
Labels: refactoring

#48 fixed context_type passing to options
  lib/lt/lcms/metadata/base_service.rb
Labels: bug

#49 Handle infinite loop for some tags
  lib/doc_template/document.rb
  lib/doc_template/tags/base_tag.rb
Labels: enhancement
